spring:
  application:
    name: pos-order
  cloud:
    function:
      definition: placeOrder
    stream:
      function:
        bindings:
          deliver-order: String
      bindings:
        loan:
          destination: output

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/